# Generated by Django 5.0.1 on 2024-02-09 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_is_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cover',
            field=models.ImageField(blank=True, default='tests/tests_recipes/imagem_temporaria.jpg', upload_to='media/covers/%Y/%m/%d'),
        ),
    ]
