# Generated by Django 5.0.1 on 2024-02-17 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_recipe_cover_alter_recipe_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name': 'Receitas', 'verbose_name_plural': 'Receitas'},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cover',
            field=models.ImageField(default='tests/tests_recipes/imagem_temporaria.jpg', upload_to='media/covers/%Y/%m/%d', verbose_name='Capa'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.CharField(max_length=165, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='preparation_step',
            field=models.TextField(verbose_name='Passos do Preparo'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='preparation_time',
            field=models.IntegerField(verbose_name='Tempo de Preparo'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='preparation_time_unit',
            field=models.CharField(max_length=65, verbose_name='Unidade do Tempo de Preparo'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='servings',
            field=models.IntegerField(verbose_name='Porções'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='servings_unit',
            field=models.CharField(max_length=65, verbose_name='Unidade das Porções'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=65, verbose_name='Título'),
        ),
    ]
