# Generated by Django 5.0.1 on 2024-02-18 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_alter_recipe_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cover',
            field=models.ImageField(blank=True, default='test/tests_recipes/imagem_generica.jpg', upload_to='media/covers/%Y/%m/%d', verbose_name='Capa'),
        ),
    ]
